/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export type CreateLibraryType =
  (typeof CreateLibraryType)[keyof typeof CreateLibraryType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateLibraryType = {
  MOVIES: "MOVIES",
  TV_SHOWS: "TV_SHOWS",
} as const;
