/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */
import type { CreateLibraryDTOType } from "./createLibraryDTOType";

export interface CreateLibraryDTO {
  name: string;
  path: string;
  type: CreateLibraryDTOType;
}
