/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export type CreateLibraryDTOType =
  (typeof CreateLibraryDTOType)[keyof typeof CreateLibraryDTOType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateLibraryDTOType = {
  MOVIES: "MOVIES",
  TV_SHOWS: "TV_SHOWS",
} as const;
