/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { CreateLibraryType } from "./createLibraryType";

export interface CreateLibrary {
  name: string;
  path: string;
  type: CreateLibraryType;
}
