/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export type EditLibraryPermissionsAddItemAccess =
  (typeof EditLibraryPermissionsAddItemAccess)[keyof typeof EditLibraryPermissionsAddItemAccess];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EditLibraryPermissionsAddItemAccess = {
  READ: "READ",
  WRITE: "WRITE",
} as const;
