/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { EditLibraryPermissionsRemoveItemAccess } from "./editLibraryPermissionsRemoveItemAccess";

export type EditLibraryPermissionsRemoveItem = {
  access: EditLibraryPermissionsRemoveItemAccess;
  userId: string;
};
