/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { EditLibraryPermissionsAddItem } from "./editLibraryPermissionsAddItem";
import type { EditLibraryPermissionsRemoveItem } from "./editLibraryPermissionsRemoveItem";

export interface EditLibraryPermissions {
  add?: EditLibraryPermissionsAddItem[];
  libraryId: string;
  remove?: EditLibraryPermissionsRemoveItem[];
}
