/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */

export interface EpisodeDTO {
  episode_number: number;
  id: string;
  image: string | null;
  mediaId: string;
  name: string;
  overview: string | null;
  seasonId: string | null;
}
