/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */
import type { GetLibraryContent200OneOfItem } from "./getLibraryContent200OneOfItem";
import type { GetLibraryContent200OneOfTwoItem } from "./getLibraryContent200OneOfTwoItem";

export type GetLibraryContent200 =
  | GetLibraryContent200OneOfItem[]
  | GetLibraryContent200OneOfTwoItem[];
