/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { LibraryContentShowData } from "./libraryContentShowData";
import type { LibraryContentShowType } from "./libraryContentShowType";

export interface LibraryContentShow {
  data: LibraryContentShowData;
  type: LibraryContentShowType;
}
