/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */

export type LibraryType = (typeof LibraryType)[keyof typeof LibraryType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LibraryType = {
  MOVIES: "MOVIES",
  TV_SHOWS: "TV_SHOWS",
} as const;
