/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */
import type { LibraryContentMovieData } from "./libraryContentMovieData";
import type { LibraryContentMovieType } from "./libraryContentMovieType";

export interface LibraryContentMovie {
  data: LibraryContentMovieData;
  type: LibraryContentMovieType;
}
