/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export type LibraryContentMovieType =
  (typeof LibraryContentMovieType)[keyof typeof LibraryContentMovieType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LibraryContentMovieType = {
  MOVIES: "MOVIES",
} as const;
