/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */
import type { LibraryType } from "./libraryType";

export interface LibraryDTO {
  createdAt: string;
  id: string;
  name: string;
  path: string;
  type: LibraryType;
}
