/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export type LibraryAccessType =
  (typeof LibraryAccessType)[keyof typeof LibraryAccessType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LibraryAccessType = {
  READ: "READ",
  WRITE: "WRITE",
} as const;
