/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */
import type { LibraryContentShow } from "./libraryContentShow";
import type { LibraryContentMovie } from "./libraryContentMovie";

export type LibraryContent = LibraryContentShow[] | LibraryContentMovie[];
