/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */

export type LibraryContentMovieDataItem = {
  id: string;
  libraryId: string;
  mediaId: string;
  name: string;
  overview: string | null;
};
