/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { LibraryAccessAccess } from "./libraryAccessAccess";
import type { User } from "./user";

export interface LibraryAccess {
  access: LibraryAccessAccess;
  user?: User;
}
