/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { Movie } from "./movie";
import type { MediaContextDataBaseOneOfThreeType } from "./mediaContextDataBaseOneOfThreeType";

export type MediaContextDataBaseOneOfThree = {
  movie: Movie;
  type: MediaContextDataBaseOneOfThreeType;
};
