/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export interface MediaDTO {
  bitrate: number;
  createdAt: string;
  duration: number;
  height: number;
  id: string;
  libraryId: string;
  path: string;
  width: number;
}
