/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { MediaStreamType } from "./mediaStreamType";

export interface MediaStream {
  name: string;
  streamIndex: number;
  type: MediaStreamType;
}
