/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export type MediaContextDataBaseOneOfThreeType =
  (typeof MediaContextDataBaseOneOfThreeType)[keyof typeof MediaContextDataBaseOneOfThreeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaContextDataBaseOneOfThreeType = {
  MOVIES: "MOVIES",
} as const;
