/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { Episode } from "./episode";
import type { Season } from "./season";
import type { Show } from "./show";
import type { MediaContextDataBaseOneOfType } from "./mediaContextDataBaseOneOfType";

export type MediaContextDataBaseOneOf = {
  episode: Episode;
  season: Season;
  show: Show;
  type: MediaContextDataBaseOneOfType;
};
