/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export type MediaContextDataBaseOneOfType =
  (typeof MediaContextDataBaseOneOfType)[keyof typeof MediaContextDataBaseOneOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaContextDataBaseOneOfType = {
  TV_SHOWS: "TV_SHOWS",
} as const;
