/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export type MediaStreamType =
  (typeof MediaStreamType)[keyof typeof MediaStreamType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaStreamType = {
  audio: "audio",
  subtitle: "subtitle",
  video: "video",
  attachment: "attachment",
} as const;
