/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export interface MovieDTO {
  id: string;
  images: string[];
  libraryId: string;
  mediaId: string;
  name: string;
  overview: string | null;
  tmdbId: number;
}
