/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export type PlayerSettingStreamType =
  (typeof PlayerSettingStreamType)[keyof typeof PlayerSettingStreamType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayerSettingStreamType = {
  video: "video",
  audio: "audio",
  subtitle: "subtitle",
} as const;
