/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */
import type { AuthTokens } from "./authTokens";

export type PostAuthLogin201 = boolean | AuthTokens;
