/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { PostLibraryNew201OneOf } from "./postLibraryNew201OneOf";

export type PostLibraryNew201 = boolean | PostLibraryNew201OneOf;
