/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { LibraryAccessType } from "./libraryAccessType";

export type PostLibraryAccess201Item = {
  access: LibraryAccessType;
  id: string;
  libraryId: string;
  userId: string;
};
