/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { Episode } from "./episode";

export interface SeasonWithEpisodes {
  episodes: Episode[];
  id: string;
  images: string[];
  name: string;
  overview: string | null;
  season_number: number;
}
