/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export type SeasonWithEpisodesEpisodesItem = {
  episode_number: number;
  id: string;
  images: string[];
  mediaId: string;
  name: string;
  overview: string | null;
  seasonId: string | null;
};
