/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */

export interface Show {
  id: string;
  images: string[];
  name: string;
  overview: string | null;
  path: string;
  tvmazeId: number;
}
