/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */
import type { ShowWithSeasonsSeasonsItem } from "./showWithSeasonsSeasonsItem";

export interface ShowWithSeasons {
  id: string;
  images: string[];
  libraryId: string;
  name: string;
  overview: string | null;
  seasons: ShowWithSeasonsSeasonsItem[];
  tvmazeId: number;
}
