/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */

export type ShowWithSeasonsSeasonsItem = {
  id: string;
  image: string | null;
  name: string;
  overview: string | null;
  season_number: number;
  showId: string;
};
