/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/server
 * OpenAPI spec version: 0.0.1
 */
import type { PlayerResolution } from "./playerResolution";
import type { PlayerSettings } from "./playerSettings";

export interface StartedPlayerInfos {
  availableResolutions: PlayerResolution[];
  id: string;
  settings: PlayerSettings;
}
