/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */
import type { TypeMOVIESidstringnamestringoverviewstringnullmediaIdstringlibraryIdstringType } from "./typeMOVIESidstringnamestringoverviewstringnullmediaIdstringlibraryIdstringType";

export interface TypeMOVIESidstringnamestringoverviewstringnullmediaIdstringlibraryIdstring {
  id: string;
  libraryId: string;
  mediaId: string;
  name: string;
  overview: string | null;
  type: TypeMOVIESidstringnamestringoverviewstringnullmediaIdstringlibraryIdstringType;
}
