/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */

export type TypeMOVIESidstringnamestringoverviewstringnullmediaIdstringlibraryIdstringType =
  (typeof TypeMOVIESidstringnamestringoverviewstringnullmediaIdstringlibraryIdstringType)[keyof typeof TypeMOVIESidstringnamestringoverviewstringnullmediaIdstringlibraryIdstringType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeMOVIESidstringnamestringoverviewstringnullmediaIdstringlibraryIdstringType =
  {
    MOVIES: "MOVIES",
  } as const;
