/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */

export type TypeTVSHOWSidstringnamestringoverviewstringnulllibraryIdstringType =
  (typeof TypeTVSHOWSidstringnamestringoverviewstringnulllibraryIdstringType)[keyof typeof TypeTVSHOWSidstringnamestringoverviewstringnulllibraryIdstringType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeTVSHOWSidstringnamestringoverviewstringnulllibraryIdstringType =
  {
    TV_SHOWS: "TV_SHOWS",
  } as const;
