/**
 * Generated by otqs v1.0.0 🍺
 * Do not edit manually.
 * @beast/backend
 * OpenAPI spec version: 0.0.1
 */
import type { TypeTVSHOWSidstringnamestringoverviewstringnulllibraryIdstringType } from "./typeTVSHOWSidstringnamestringoverviewstringnulllibraryIdstringType";

export interface TypeTVSHOWSidstringnamestringoverviewstringnulllibraryIdstring {
  id: string;
  libraryId: string;
  name: string;
  overview: string | null;
  type: TypeTVSHOWSidstringnamestringoverviewstringnulllibraryIdstringType;
}
